name: Sync Forked Repo

on:
  push:
    branches:
      - main   

env:
  TARGET_ACCOUNT: seitcMty

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Update Fork
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          ACCOUNT=${{env.TARGET_ACCOUNT}}
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$ACCOUNT/$REPO_NAME/merge-upstream \
          -d '{"branch": "main"}'
